/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ChinaTown.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube045_2: THREE.Mesh;
    Cube045_3: THREE.Mesh;
    Cube045_4: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube043: THREE.Mesh;
    Cube044: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube059_1: THREE.Mesh;
    Cube059_2: THREE.Mesh;
    Cube059_3: THREE.Mesh;
    Cube059_4: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ChinaTown.glb') as GLTFResult;
  const modelRef = useRef<Group>(null);
  useFrame(() => {
    if (modelRef.current !== null) modelRef.current.rotation.y += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={modelRef} position={[0, -2, 0]}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 0, -2.5]}
        scale={[0.5, 0.25, 0.5]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[0, 0, -6]}
        scale={[0.5, 0.25, 0.5]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[0, 0, 2.5]}
        scale={[0.5, 0.25, 0.5]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[0, 0, 6]}
        scale={[0.5, 0.25, 0.5]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        position={[0, 0.5, -6]}
        scale={[0.38, 1.75, 0.38]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[0, 0.5, 6]}
        scale={[0.38, 1.75, 0.38]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
        position={[0, 0.5, 2.5]}
        scale={[0.38, 1.75, 0.38]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.002']}
        position={[0, 0.5, -2.5]}
        scale={[0.38, 1.75, 0.38]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Material.001']}
        position={[0.4, 0.5, 2.5]}
        scale={[0.03, 0.75, 0.2]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials['Material.001']}
        position={[0.4, 0.5, -2.5]}
        scale={[0.03, 0.75, 0.2]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.003']}
        position={[0, 4, 2.5]}
        scale={[0.38, 0.25, 0.38]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials['Material.003']}
        position={[0, 4, -2.5]}
        scale={[0.38, 0.25, 0.38]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.003']}
        position={[0, 3.5, 0]}
        scale={[0.25, 0.25, 2.13]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Material.002']}
        position={[0, 4, 0]}
        scale={[0.1, 0.25, 2.13]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Material.002']}
        position={[0, 3.75, 4.38]}
        scale={[0.1, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials['Material.001']}
        position={[0, 3.25, 4.38]}
        scale={[0.25, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials['Material.002']}
        position={[0, 3.75, -4.38]}
        scale={[0.1, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials['Material.001']}
        position={[0, 3.25, -4.38]}
        scale={[0.25, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials['Material.003']}
        position={[0, 4.25, 4.68]}
        scale={[0.35, 0.25, 1.8]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials['Material.003']}
        position={[0, 4.25, -4.68]}
        scale={[0.35, 0.25, 1.8]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Material.001']}
        position={[0, 4.75, 0]}
        scale={[0.38, 0.25, 3]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Material.001']}
        position={[0, 5.6, 0]}
        scale={[0.15, 0.6, 1.2]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Material.002']}
        position={[0, 5.6, 1.38]}
        scale={[0.38, 0.6, 0.17]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials['Material.002']}
        position={[0, 5.6, -1.38]}
        scale={[0.38, 0.6, 0.17]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Material.004']}
        position={[0, 6.45, 0]}
        scale={[0.38, 0.25, 1.55]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials['Material.004']}
        position={[0, 5.6, 0]}
        scale={[0.15, 0.6, 1.2]}
      />
      <group position={[0, 5.26, 1.55]} scale={[0.13, 0.28, 0.07]}>
        <mesh
          geometry={nodes.Cube045.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube045_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube045_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube045_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Cube045_4.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials['Material.003']}
        position={[0, 6.87, 0]}
        scale={[0.13, 0.28, 0.07]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials['Material.003']}
        position={[0, 6.87, -0.6]}
        scale={[0.13, 0.28, 0.07]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials['Material.003']}
        position={[0, 6.87, 0.6]}
        scale={[0.13, 0.28, 0.07]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials['Material.003']}
        position={[0, 6.87, 1.2]}
        scale={[0.13, 0.28, 0.07]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials['Material.003']}
        position={[0, 6.87, -1.2]}
        scale={[0.13, 0.28, 0.07]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials['Material.005']}
        position={[0, 7.92, 0]}
        scale={[0.06, 0.12, 1.22]}
      />
      <group
        position={[0, 5.26, -1.55]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.13, 0.28, 0.07]}
      >
        <mesh
          geometry={nodes.Cube059.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube059_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube059_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube059_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Cube059_4.geometry}
          material={materials['Material.005']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/ChinaTown.glb');
