/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Gwanghwamun.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Text_1: THREE.Mesh;
    Text_2: THREE.Mesh;
    Text_3: THREE.Mesh;
    Cube005_1: THREE.Mesh;
    Cube005_2: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube043_1: THREE.Mesh;
    Cube043_2: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube050_1: THREE.Mesh;
    Cube051_1: THREE.Mesh;
    Cube051_2: THREE.Mesh;
    Cube052_1: THREE.Mesh;
    Cube052_2: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Cube053_2: THREE.Mesh;
    Cube054_1: THREE.Mesh;
    Cube054_2: THREE.Mesh;
    Cube055_1: THREE.Mesh;
    Cube055_2: THREE.Mesh;
    Cube056_1: THREE.Mesh;
    Cube056_2: THREE.Mesh;
    Cube057_1: THREE.Mesh;
    Cube057_2: THREE.Mesh;
    Cube058_1: THREE.Mesh;
    Cube058_2: THREE.Mesh;
    Cube059_1: THREE.Mesh;
    Cube059_2: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube061_1: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube062_1: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube063_1: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube064_1: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube065_1: THREE.Mesh;
    Cube066_1: THREE.Mesh;
    Cube066_2: THREE.Mesh;
    Cube067: THREE.Mesh;
    Cube067_1: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cube068_1: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube069_1: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube070_1: THREE.Mesh;
    Cube079_1: THREE.Mesh;
    Cube079_2: THREE.Mesh;
    Cube071: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube073: THREE.Mesh;
    Cube074: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube077: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube095: THREE.Mesh;
    Cube095_1: THREE.Mesh;
    Cube097: THREE.Mesh;
    Cube097_1: THREE.Mesh;
    Cube104: THREE.Mesh;
    Cube104_1: THREE.Mesh;
    Cube105: THREE.Mesh;
    Cube105_1: THREE.Mesh;
    Cube106: THREE.Mesh;
    Cube106_1: THREE.Mesh;
    Cube107: THREE.Mesh;
    Cube107_1: THREE.Mesh;
    Cube108: THREE.Mesh;
    Cube108_1: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube117: THREE.Mesh;
    Cube117_1: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube119: THREE.Mesh;
    Cube119_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube121: THREE.Mesh;
    Cube121_1: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube123: THREE.Mesh;
    Cube123_1: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube133: THREE.Mesh;
    Cube133_1: THREE.Mesh;
    Cube134: THREE.Mesh;
    Cube134_1: THREE.Mesh;
  };
  materials: {
    black: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    Gray: THREE.MeshStandardMaterial;
    indigo: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['light green']: THREE.MeshStandardMaterial;
    green: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
  };
};

export default function Model({ transX, transY }: any) {
  const { nodes, materials } = useGLTF('/models/Gwanghwamun.glb') as GLTFResult;
  const modelRef = useRef<Group>(null);
  useFrame(() => {
    if (modelRef.current !== null && transX && transY) {
      modelRef.current.rotation.y += transX / 3000;
      modelRef.current.rotation.x += transY / 3000;
    }
  });
  return (
    <group dispose={null} ref={modelRef} position={[0, -2, -4]}>
      <group position={[0, 4.12, 0.83]} rotation={[1.83, 0, 0]} scale={0.23}>
        <mesh geometry={nodes.Text_1.geometry} material={materials.black} />
        <mesh geometry={nodes.Text_2.geometry} material={materials.brown} />
        <mesh geometry={nodes.Text_3.geometry} material={materials.white} />
      </group>
      <group scale={[3, 1.1, 1]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Gray} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Gray} />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.indigo}
        position={[0, 2.05, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.75, 0.01, 0.15]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[0, 2.05, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.75, 0.01, 0.15]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['light green']}
        position={[0, 2.2, 0]}
        scale={[2.75, 0.4, 0.75]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.indigo}
        position={[0, 3, 0]}
        scale={[3.5, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.green}
        position={[0, 2.2, 0.75]}
        scale={[2.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.green}
        position={[0, 2.75, 0.75]}
        scale={[2.75, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.002']}
        position={[0, 2.63, 0.75]}
        scale={[0.03, 0.13, 0.01]}
      />
      <group position={[2.51, 2.88, 0.78]} scale={[0.025, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube043_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube043_2.geometry}
          material={materials['light green']}
        />
      </group>
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials['light green']}
        position={[0, 3.5, 0]}
        scale={[2.75, 0.4, 0.75]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.indigo}
        position={[0, 4.3, 0]}
        scale={[3.5, 0.25, 1.5]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.green}
        position={[0, 4.05, 0.75]}
        scale={[2.75, 0.13, 0.01]}
      />
      <group position={[-0.46, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube050.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube050_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-0.69, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube051_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube051_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-0.92, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube052_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube052_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-1.15, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube053_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube053_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-1.37, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube054_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube054_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-1.59, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube055_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube055_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-1.82, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube056_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube056_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[2.05, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube057_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube057_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[2.28, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube058_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube058_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-2.51, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube059_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube059_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[0.46, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube061.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube061_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[0.69, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube062.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube062_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[0.92, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube063.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube063_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[1.15, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube064.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube064_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[1.37, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube065.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube065_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[1.59, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube066_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube066_2.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[1.82, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube067.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube067_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-2.05, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube068.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube068_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[-2.28, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube069.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube069_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[2.51, 4.18, 0.78]} scale={[0.03, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube070.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube070_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group position={[0, 3.65, 0.76]} scale={[0.25, 0.1, 0.01]}>
        <mesh
          geometry={nodes.Cube079_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube079_2.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        geometry={nodes.Cube071.geometry}
        material={materials.green}
        position={[-2.75, 2.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube072.geometry}
        material={materials.green}
        position={[2.75, 2.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube073.geometry}
        material={materials.green}
        position={[2.75, 2.75, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube074.geometry}
        material={materials.green}
        position={[0, 2.2, -0.75]}
        scale={[2.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube075.geometry}
        material={materials.green}
        position={[-2.75, 2.75, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube076.geometry}
        material={materials.green}
        position={[0, 2.75, -0.75]}
        scale={[2.75, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube077.geometry}
        material={materials['Material.002']}
        position={[2.75, 2.5, -0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube078.geometry}
        material={materials['Material.002']}
        position={[2.75, 2.5, 0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube079.geometry}
        material={materials['Material.002']}
        position={[-2.75, 2.5, 0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube080.geometry}
        material={materials['Material.002']}
        position={[-2.75, 2.5, -0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <group
        position={[-2.78, 2.88, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube095.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube095_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[-2.78, 2.88, -0.23]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube097.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube097_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[2.77, 2.87, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube104.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube104_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[-2.78, 2.88, -0.46]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube105.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube105_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[-2.78, 2.88, 0.23]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube106.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube106_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[-2.78, 2.88, 0.46]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube107.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube107_1.geometry}
          material={materials['light green']}
        />
      </group>
      <group
        position={[-2.51, 2.88, -0.78]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.025, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube108.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube108_1.geometry}
          material={materials['light green']}
        />
      </group>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials['Material.002']}
        position={[0, 2.63, -0.75]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.002']}
        position={[-2.75, 3.5, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials['Material.002']}
        position={[2.75, 3.5, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.15, 0.01]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials['Material.003']}
        position={[-2.77, 3.65, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.2, 0.1, 0.01]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Material.003']}
        position={[2.77, 3.65, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.2, 0.1, 0.01]}
      />
      <group
        position={[0, 3.65, -0.76]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.25, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube117.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube117_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.green}
        position={[0, 4.05, -0.75]}
        scale={[2.75, 0.13, 0.01]}
      />
      <group
        position={[-2.51, 4.18, -0.78]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.025, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube119.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube119_1.geometry}
          material={materials['light green']}
        />
      </group>
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials.green}
        position={[2.75, 4.05, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.13, 0.01]}
      />
      <group
        position={[2.77, 4.18, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube121.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube121_1.geometry}
          material={materials['light green']}
        />
      </group>
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.green}
        position={[-2.75, 4.05, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.75, 0.13, 0.01]}
      />
      <group
        position={[-2.77, 4.18, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.1, 0.01]}
      >
        <mesh
          geometry={nodes.Cube123.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube123_1.geometry}
          material={materials['light green']}
        />
      </group>
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials['Material.002']}
        position={[-2.75, 3.8, 0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials['Material.002']}
        position={[-2.75, 3.8, -0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials['Material.002']}
        position={[2.75, 3.8, -0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Material.002']}
        position={[2.75, 3.8, 0.4]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Material.002']}
        position={[0, 3.93, 0.75]}
        scale={[0.03, 0.13, 0.01]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Material.002']}
        position={[0, 3.93, -0.75]}
        scale={[0.03, 0.13, 0.01]}
      />
      <group position={[-4, 1.8, 0]} scale={[1, 0.25, 0.8]}>
        <mesh geometry={nodes.Cube133.geometry} material={materials.indigo} />
        <mesh geometry={nodes.Cube133_1.geometry} material={materials.Gray} />
      </group>
      <group position={[4, 1.8, 0]} scale={[1, 0.25, 0.8]}>
        <mesh geometry={nodes.Cube134.geometry} material={materials.indigo} />
        <mesh geometry={nodes.Cube134_1.geometry} material={materials.Gray} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Gwanghwamun.glb');
