/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 OlympicPark.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
    Cube013_3: THREE.Mesh;
    Cube013_4: THREE.Mesh;
    Cube013_5: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
  };
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/OlympicPark.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2, 0]}>
      <group
        position={[0, 2.59, 1.4]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0, -0.15]}
      >
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials['Material.006']}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube013_3.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube013_4.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Cube013_5.geometry}
          material={materials['Material.005']}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['Material.007']}
        position={[0, 2.59, 1.4]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0, -0.15]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Material.007']}
        position={[0, 2.59, 1.4]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0, -0.15]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.007']}
        position={[0, 2.59, 1.4]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0, -0.15]}
      />
    </group>
  );
}

useGLTF.preload('/models/OlympicPark.glb');
