/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Seokguram.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002_1: THREE.Mesh;
    Cylinder002_2: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export default function Model({ transX, transY }: any) {
  const { nodes, materials } = useGLTF('/models/Seokguram.glb') as GLTFResult;
  const modelRef = useRef<Group>(null);
  useFrame(() => {
    if (modelRef.current !== null && transX && transY) {
      modelRef.current.rotation.y += transX / 3000;
      modelRef.current.rotation.x += transY / 3000;
    }
  });
  return (
    <group dispose={null} ref={modelRef} position={[0, -1.4, 0]} receiveShadow>
      <group position={[0, 1.04, 0]} scale={[1.2, 0.1, 1.2]}>
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cylinder002_2.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Seokguram.glb');
