/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Seokguram.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube030: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Seokguram.glb') as GLTFResult;
  const modelRef = useRef<Group>(null);
  useFrame(() => {
    if (modelRef.current !== null) modelRef.current.rotation.y += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={modelRef} position={[0, -1, 0]}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        scale={[1.5, 0.03, 1.5]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[0, 0.05, 0]}
        scale={[1.4, 0.04, 1.4]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.001']}
        position={[0, 0.12, 0]}
        scale={[1.2, 0.1, 1.2]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.001']}
        position={[0, 0.42, 0]}
        scale={[1.1, 0.03, 1.1]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.001']}
        position={[0, 0.47, 0]}
        scale={[1, 0.04, 1]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.001']}
        position={[0, 0.54, 0]}
        scale={[0.9, 0.04, 0.9]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials['Material.001']}
        position={[0, 0.61, 0]}
        scale={[0.8, 0.25, 0.8]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials['Material.001']}
        position={[0, 1.11, 0]}
        scale={[0.9, 0.03, 0.9]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials['Material.001']}
        position={[0, 1.16, 0]}
        scale={[1, 0.04, 1]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.001']}
        position={[0, 0.32, 0]}
        scale={[1.2, 0.05, 1.2]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.001']}
        position={[0, 1.23, 0]}
        scale={[1.1, 0.03, 1.1]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials['Material.001']}
        position={[0, 1.38, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[1.2, 0.05, 1.2]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials['Material.001']}
        position={[0, 1.38, 0]}
        scale={[1.2, 0.1, 1.2]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[0, 0.61, -0.8]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        position={[0, 0.61, 0.8]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[0.8, 0.61, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.001']}
        position={[-0.8, 0.61, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.001']}
        position={[-0.56, 0.61, -0.56]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.001']}
        position={[0.56, 0.61, -0.56]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Material.001']}
        position={[0.56, 0.61, 0.56]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials['Material.001']}
        position={[-0.56, 0.61, 0.56]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.05, 0.25, 0.05]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.001']}
        position={[0.08, 1.21, 0]}
        scale={[0.4, 0.83, 0.5]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.001']}
        position={[-0.45, 1.65, 0.69]}
        rotation={[-Math.PI, 0.86, -Math.PI]}
        scale={[0.2, 0.15, 0.15]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials['Material.001']}
        position={[-0.49, 1.65, -0.68]}
        rotation={[0, 0.99, 0]}
        scale={[0.2, 0.15, 0.15]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials['Material.001']}
        position={[-0.49, 1.64, -0.69]}
        rotation={[-0.2, 0.17, 0.02]}
        scale={[0.2, 0.15, 0.15]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials['Material.001']}
        position={[-0.45, 1.64, 0.7]}
        rotation={[-2.94, 0.27, -0.03]}
        scale={[0.2, 0.15, 0.15]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials['Material.001']}
        position={[-0.55, 1.86, 0.42]}
        rotation={[-1.79, -0.3, 0.81]}
        scale={[0.19, 0.06, 0.08]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.001']}
        position={[-0.45, 1.83, -0.34]}
        rotation={[1.34, -0.3, 0.65]}
        scale={[0.19, 0.06, 0.08]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials['Material.001']}
        position={[0.08, 1.98, 0]}
        scale={[0.48, 0.48, 0.66]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.001']}
        position={[0.19, 2.38, -0.59]}
        rotation={[-1.4, 0.24, 1.53]}
        scale={[0.18, 0.18, 0.36]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Material.001']}
        position={[0.08, 2.36, -0.47]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Material.001']}
        position={[0.08, 2.36, 0.47]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials['Material.001']}
        position={[-0.05, 2.05, -0.64]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials['Material.001']}
        position={[-0.22, 1.91, -0.67]}
        rotation={[-1.35, 1, 1.38]}
        scale={[0.12, 0.12, 0.48]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials['Material.001']}
        position={[-0.69, 1.79, -0.7]}
        rotation={[Math.PI / 2, 0.64, -Math.PI / 2]}
        scale={[0.12, 0.11, 0.09]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials['Material.001']}
        position={[-0.62, 1.81, -0.59]}
        rotation={[-1.49, 0.83, -0.06]}
        scale={[0.09, 0.11, 0.18]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Material.001']}
        position={[-0.55, 1.9, -0.61]}
        rotation={[0, 0, 2.56]}
        scale={[0.06, 0.09, 0.06]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials['Material.001']}
        position={[0.08, 2.38, 0.42]}
        rotation={[1.48, -0.28, -0.03]}
        scale={[0.18, 0.18, 0.36]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials['Material.001']}
        position={[0.02, 2.08, 0.61]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials['Material.001']}
        position={[-0.17, 1.91, 0.43]}
        rotation={[2.55, -0.48, -3.11]}
        scale={[0.12, 0.12, 0.48]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials['Material.001']}
        position={[-0.46, 1.86, 0.06]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.11, 0.09]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials['Material.001']}
        position={[-0.45, 1.86, -0.05]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.09, 0.11, 0.18]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials['Material.001']}
        position={[-0.44, 1.84, 0.09]}
        rotation={[-1.15, 0, 0]}
        scale={[0.06, 0.09, 0.06]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Material.001']}
        position={[0.04, 2.8, 0]}
        scale={[0.24, 0.36, 0.3]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Material.001']}
        position={[0.1, 2.72, 0]}
        scale={[0.12, 0.18, 0.12]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Material.001']}
        position={[0.04, 3.09, -0.27]}
        scale={[0.03, 0.12, 0.06]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials['Material.001']}
        position={[0.04, 3, -0.27]}
        scale={[0.03, 0.12, 0.04]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials['Material.001']}
        position={[0.04, 3.09, 0.27]}
        scale={[0.03, 0.12, 0.06]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials['Material.001']}
        position={[0.04, 3, 0.27]}
        scale={[0.03, 0.12, 0.04]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials['Material.001']}
        position={[0.06, 3.36, 0]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
        position={[-0.33, 2.32, -0.17]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.5, 1, 0.5]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Material.002']}
        position={[0.48, 2.26, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.5, 1, 0.5]}
      />
    </group>
  );
}

useGLTF.preload('/models/Seokguram.glb');
