/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sungnyemun.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube003: THREE.Mesh;
  };
  materials: {
    ['Material.018']: THREE.MeshStandardMaterial;
    ['Material.016']: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sungnyemun.glb') as GLTFResult;
  const sungnyemunRef = useRef<Group>(null);
  useFrame(() => {
    if (sungnyemunRef.current !== null)
      sungnyemunRef.current.rotation.y += 0.01;
  });
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group {...props} dispose={null} ref={sungnyemunRef}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.018']}
        position={[0, 2.12, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -0.6, -0.5]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Material.016']}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -0.6, -0.5]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.018']}
        position={[0, 1.55, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2.1, -0.63, -0.53]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.017']}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -0.6, -0.5]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Material.003']}
        position={[0, 2.4, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -0.6, -0.5]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Material.017']}
        position={[0, -0.6, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2, -0.6, -0.5]}
      />
    </group>
  );
}

useGLTF.preload('/models/sungnyemun.glb');
