/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cheongwadae.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder029_1: THREE.Mesh;
    Cylinder029_2: THREE.Mesh;
    Cylinder029_3: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Cheongwadae.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.2, 0]} receiveShadow>
      <group position={[0, 1.16, 0]} scale={[0.1, 0.5, 0.1]}>
        <mesh
          geometry={nodes.Cylinder029_1.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cylinder029_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cylinder029_3.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Cheongwadae.glb');
