/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cheomseongdae.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube004_2: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/Cheomseongdae.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.5, 0]} receiveShadow>
      <group position={[0, 3, 0]} scale={[0.75, 0.13, 0.75]}>
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Cheomseongdae.glb');
