/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cheomseongdae.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Group } from 'three';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder_3: THREE.Mesh;
  };
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model() {
  const { nodes, materials } = useGLTF(
    '/models/Cheomseongdae.glb'
  ) as GLTFResult;
  return (
    <group dispose={null} position={[0, -2, 0]} receiveShadow>
      <group rotation={[0, -Math.PI / 2, 0]} scale={[1, 2.5, 1]}>
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Cheomseongdae.glb');
