/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 LotteTower.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/LotteTower.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -3, 0]} receiveShadow>
      <group scale={[0.94, 2.81, 0.94]}>
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/LotteTower.glb');
