/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotBuilding63.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube004: THREE.Mesh;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/NotBuilding63.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.01, 0.03, 0.19]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotBuilding63.glb');
