/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotChinaTown.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotChinaTown.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -3, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 4.18, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.5, 0.25, 0.5]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotChinaTown.glb');
