/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotCheongwadae.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder029: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotCheongwadae.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.2, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={materials.Material}
        position={[0, 1.16, 0]}
        scale={[0.1, 0.5, 0.1]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotCheongwadae.glb');
