/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotGwanghwamun.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text_1: THREE.Mesh;
    Text_2: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotGwanghwamun.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -2, 0]} receiveShadow>
      <group rotation={[1.83, 0, 0]} scale={0.23}>
        <mesh geometry={nodes.Text_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Text_2.geometry} material={materials.Material} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/NotGwanghwamun.glb');
