/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotLotteTower.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotLotteTower.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -3, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.Material}
        scale={[0.94, 2.81, 0.94]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotLotteTower.glb');
