/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotOlympicPark.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotOlympicPark.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.5, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[2.25, 2.7, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 0.15, 1.25]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotOlympicPark.glb');
