/* eslint-disable react/no-unknown-property */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotSungnyemun.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/NotSungnyemun.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.2, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        rotation={[2.19, 0, 0]}
        scale={[0.06, 0.01, 0.13]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotSungnyemun.glb');
