/* eslint-disable react/no-unknown-property */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NotSeongsan.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/NotSeongsan.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1, 0]} receiveShadow>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.Material}
        position={[0, 0.11, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 0.23, 1]}
      />
    </group>
  );
}

useGLTF.preload('/models/NotSeongsan.glb');
