/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 OlympicPark.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube006_3: THREE.Mesh;
    Cube006_4: THREE.Mesh;
    Cube006_5: THREE.Mesh;
    Cube006_6: THREE.Mesh;
    Cube006_7: THREE.Mesh;
    Cube006_8: THREE.Mesh;
    Cube006_9: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/OlympicPark.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.5, 0]} receiveShadow>
      <group
        position={[2.25, 2.7, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 0.15, 1.25]}
      >
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube006_1.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Cube006_2.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Cube006_3.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube006_4.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Cube006_5.geometry}
          material={materials['Material.014']}
        />
        <mesh
          geometry={nodes.Cube006_6.geometry}
          material={materials['Material.010']}
        />
        <mesh
          geometry={nodes.Cube006_7.geometry}
          material={materials['Material.011']}
        />
        <mesh
          geometry={nodes.Cube006_8.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Cube006_9.geometry}
          material={materials['Material.013']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/OlympicPark.glb');
