/* eslint-disable react/no-unknown-property */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Sungnyemun.glb --types
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube007: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    Cube007_3: THREE.Mesh;
    Cube007_4: THREE.Mesh;
    Cube007_5: THREE.Mesh;
    Cube007_6: THREE.Mesh;
  };
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.019']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Sungnyemun.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, -1.2, 0]} receiveShadow>
      <group rotation={[2.19, 0, 0]} scale={[0.06, 0.01, 0.13]}>
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={materials['Material.019']}
        />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube007_3.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube007_4.geometry}
          material={materials['Material.013']}
        />
        <mesh geometry={nodes.Cube007_5.geometry} material={materials.brown} />
        <mesh geometry={nodes.Cube007_6.geometry} material={materials.blue} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Sungnyemun.glb');
